title: "John Doe's Portfolio"
description: "A portfolio showcasing my work, projects, and blog posts."
baseurl: ""
url: "https://johndoe.github.io"
theme: pages-themes/hacker@v0.2.0

# Optional settings for navigation links
navbar:
  - title: "Home"
    url: "/"
  - title: "About"
    url: "/about"
  - title: "Projects"
    url: "/projects"
