title: "Hello World"
description: "A test page for myself."
baseurl: ""
url: "https://thereiam.github.io"
#theme: minima
remote_theme: jekyll/minima
plugins:
  - jekyll-remote-theme
minima:
  skin: dark

sidebar: none

navbar:
  - title: "Home"
    url: "/"
  - title: "Projects"
    url: "/projects"
