title: "Hello World"
description: "A test page for myself."
baseurl: ""
url: "https://thereiam.github.io"
theme: jekyll-theme-minimal
navbar:
  - title: "Home"
    url: "/"
  - title: "Projects"
    url: "/projects"
